version: '3.7'

services:
  minio:
    image: minio/minio:latest
    command: server --address 0.0.0.0:9010 --console-address 0.0.0.0:9011 /data
    ports:
      - "9010:9010"  # S3 API
      - "9011:9011"  # Console
    environment:
      MINIO_ROOT_USER: ozontech
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-storage:/data
    networks:
      - my_network

  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"  # HTTP
      - "9000:9000"  # TCP
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - my_network

volumes:
  minio-storage:
  clickhouse-data:

networks:
  my_network: